/**
 * Anchor IDL for the Tumar program.
 *
 * In a real deploy this file is generated by `anchor build` into
 * `target/idl/tumar.json` and copied in. We keep the TypeScript shape inline
 * so the frontend type-checks without a build step of the program.
 */

export const IDL = {
  version: "0.1.0",
  name: "tumar",
  address: "HfCmnXggSF2tVQkCrEdPNjUTBYvvC8tgbebXES2sp24Y",
  metadata: { name: "tumar", version: "0.1.0", spec: "0.1.0" },
  instructions: [
    {
      name: "initializeVault",
      discriminator: [48, 191, 163, 44, 71, 129, 63, 164],
      accounts: [
        { name: "creator", writable: true, signer: true },
        { name: "vault", writable: true },
        { name: "creatorMember", writable: true },
        { name: "systemProgram", address: "11111111111111111111111111111111" },
      ],
      args: [
        { name: "name", type: "string" },
        { name: "allocation", type: { vec: { defined: { name: "AssetAllocation" } } } },
      ],
    },
    {
      name: "joinVault",
      // sha256("global:join_vault").slice(0, 8)
      discriminator: [73, 225, 253, 176, 198, 180, 207, 152],
      accounts: [
        { name: "joiner", writable: true, signer: true },
        { name: "vault", writable: true },
        { name: "member", writable: true },
        { name: "systemProgram", address: "11111111111111111111111111111111" },
      ],
      args: [],
    },
    {
      name: "recordContribution",
      // sha256("global:record_contribution").slice(0, 8)
      discriminator: [121, 55, 143, 174, 85, 36, 104, 228],
      accounts: [
        { name: "contributor", writable: true, signer: true },
        { name: "vault", writable: true },
        { name: "member", writable: true },
        { name: "contribution", writable: true },
        { name: "systemProgram", address: "11111111111111111111111111111111" },
      ],
      args: [
        { name: "amount", type: "u64" },
        { name: "memo", type: "string" },
        // Caller-supplied seed for the Contribution PDA. Replaces the old
        // Clock::get() seed, which raced the signing window.
        { name: "nonce", type: "u64" },
      ],
    },
    {
      name: "updateAllocation",
      // sha256("global:update_allocation").slice(0, 8)
      discriminator: [173, 2, 145, 33, 101, 74, 233, 115],
      accounts: [
        { name: "creator", signer: true },
        { name: "vault", writable: true },
      ],
      args: [
        { name: "allocation", type: { vec: { defined: { name: "AssetAllocation" } } } },
      ],
    },
    {
      name: "withdraw",
      // sha256("global:withdraw").slice(0, 8)
      discriminator: [183, 18, 70, 156, 148, 109, 161, 34],
      accounts: [
        { name: "creator", writable: true, signer: true },
        { name: "vault", writable: true },
        { name: "mint" },
        { name: "vaultTokenAccount", writable: true },
        { name: "creatorTokenAccount", writable: true },
        // Token, Associated Token, System - fixed program addresses.
        { name: "tokenProgram", address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" },
        { name: "associatedTokenProgram", address: "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL" },
        { name: "systemProgram", address: "11111111111111111111111111111111" },
      ],
      args: [
        { name: "amount", type: "u64" },
      ],
    },
    {
      name: "closeVault",
      // sha256("global:close_vault").slice(0, 8)
      discriminator: [141, 103, 17, 126, 72, 75, 29, 29],
      accounts: [
        { name: "creator", writable: true, signer: true },
        { name: "vault", writable: true },
        { name: "mint" },
        { name: "vaultTokenAccount", writable: true },
        { name: "tokenProgram", address: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA" },
      ],
      args: [],
    },
    {
      name: "leaveVault",
      // sha256("global:leave_vault").slice(0, 8)
      discriminator: [89, 198, 97, 6, 231, 152, 118, 242],
      accounts: [
        { name: "owner", writable: true, signer: true },
        // UncheckedAccount - passed as a pubkey for seed derivation only.
        // The program doesn't touch the account's data, so a closed-vault
        // pubkey is valid too.
        { name: "vault" },
        { name: "member", writable: true },
      ],
      args: [],
    },
  ],
  accounts: [
    { name: "Vault", discriminator: [211, 8, 232, 43, 2, 152, 117, 119] },
    { name: "Member", discriminator: [54, 19, 162, 21, 29, 166, 17, 198] },
    { name: "Contribution", discriminator: [182, 187, 14, 111, 72, 167, 242, 212] },
  ],
  types: [
    {
      name: "AssetAllocation",
      type: {
        kind: "struct",
        fields: [
          { name: "mint", type: "pubkey" },
          { name: "bps", type: "u16" },
        ],
      },
    },
    {
      name: "Vault",
      type: {
        kind: "struct",
        fields: [
          { name: "creator", type: "pubkey" },
          { name: "name", type: "string" },
          {
            name: "allocation",
            type: { vec: { defined: { name: "AssetAllocation" } } },
          },
          { name: "usdcDeposited", type: "u64" },
          { name: "memberCount", type: "u32" },
          { name: "createdAt", type: "i64" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "Member",
      type: {
        kind: "struct",
        fields: [
          { name: "vault", type: "pubkey" },
          { name: "owner", type: "pubkey" },
          { name: "joinedAt", type: "i64" },
          { name: "contributedLifetime", type: "u64" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "Contribution",
      type: {
        kind: "struct",
        fields: [
          { name: "vault", type: "pubkey" },
          { name: "contributor", type: "pubkey" },
          { name: "amount", type: "u64" },
          { name: "timestamp", type: "i64" },
          { name: "memo", type: "string" },
          { name: "bump", type: "u8" },
        ],
      },
    },
  ],
} as const;

export type Idl = typeof IDL;
